// models.js

export const SAMSUNG_MODELS = [
  { name: "Samsung Galaxy A01 Core", code: "A013" },
  { name: "Samsung Galaxy A01", code: "A015" },
  { name: "Samsung Galaxy A02", code: "A022" },
  { name: "Samsung Galaxy A02s", code: "A025" },
  { name: "Samsung Galaxy A03 Core", code: "A032" },
  { name: "Samsung Galaxy A03", code: "A035" },
  { name: "Samsung Galaxy A03s", code: "A037" },
  { name: "Samsung Galaxy A04e", code: "A042" },
  { name: "Samsung Galaxy A04", code: "A045" },
  { name: "Samsung Galaxy A04s", code: "A047" },
  { name: "Samsung Galaxy A05", code: "A055" },
  { name: "Samsung Galaxy A05s", code: "A057" },
  { name: "Samsung Galaxy A06", code: "A065" },
  { name: "Samsung Galaxy A07", code: "A075" },
  { name: "Samsung Galaxy A10", code: "A105" },
  { name: "Samsung Galaxy A10s", code: "A107" },
  { name: "Samsung Galaxy A11", code: "A115" },
  { name: "Samsung Galaxy A12", code: "A125" },
  { name: "Samsung Galaxy A13", code: "A135" },
  { name: "Samsung Galaxy A13 5G", code: "A136" },
  { name: "Samsung Galaxy A14", code: "A145" },
  { name: "Samsung Galaxy A14 5G", code: "A146" },
  { name: "Samsung Galaxy A15", code: "A155" },
  { name: "Samsung Galaxy A15 5G", code: "A156" },
  { name: "Samsung Galaxy A16", code: "A165" },
  { name: "Samsung Galaxy A16 5G", code: "A166" },
  { name: "Samsung Galaxy A17", code: "A175" },
  { name: "Samsung Galaxy A17 5G", code: "A176" },
  { name: "Samsung Galaxy A20e", code: "A202" },
  { name: "Samsung Galaxy A20", code: "A205" },
  { name: "Samsung Galaxy A20s", code: "A207" },
  { name: "Samsung Galaxy A21", code: "A215" },
  { name: "Samsung Galaxy A21s", code: "A217" },
  { name: "Samsung Galaxy A22", code: "A225" },
  { name: "Samsung Galaxy A22 5G", code: "A226" },
  { name: "Samsung Galaxy A23", code: "A235" },
  { name: "Samsung Galaxy A23 5G", code: "A236" },
  { name: "Samsung Galaxy A24", code: "A245" },
  { name: "Samsung Galaxy A25 5G", code: "A256" },
  { name: "Samsung Galaxy A26 5G", code: "A266" },
  { name: "Samsung Galaxy A30", code: "A305" },
  { name: "Samsung Galaxy A30s", code: "A307" },
  { name: "Samsung Galaxy A31", code: "A315" },
  { name: "Samsung Galaxy A32", code: "A325" },
  { name: "Samsung Galaxy A32 5G", code: "A326" },
  { name: "Samsung Galaxy A33 5G", code: "A336" },
  { name: "Samsung Galaxy A34 5G", code: "A346" },
  { name: "Samsung Galaxy A35 5G", code: "A356" },
  { name: "Samsung Galaxy A36 5G", code: "A366" },
  { name: "Samsung Galaxy A37 5G", code: "A376" },
  { name: "Samsung Galaxy A40", code: "A405" },
  { name: "Samsung Galaxy A40s", code: "A407" },
  { name: "Samsung Galaxy A41", code: "A415" },
  { name: "Samsung Galaxy A42 5G", code: "A426" },
  { name: "Samsung Galaxy A50", code: "A505" },
  { name: "Samsung Galaxy A50s", code: "A507" },
  { name: "Samsung Galaxy A51", code: "A515" },
  { name: "Samsung Galaxy A51 5G", code: "A516" },
  { name: "Samsung Galaxy A52", code: "A525" },
  { name: "Samsung Galaxy A52 5G", code: "A526" },
  { name: "Samsung Galaxy A52s 5G", code: "A528" },
  { name: "Samsung Galaxy A53 5G", code: "A536" },
  { name: "Samsung Galaxy A54 5G", code: "A546" },
  { name: "Samsung Galaxy A55 5G", code: "A556" },
  { name: "Samsung Galaxy A56 5G", code: "A566" },
  { name: "Samsung Galaxy A57 5G", code: "A576" },
  { name: "Samsung Galaxy A6", code: "A600" },
  { name: "Samsung Galaxy A6+", code: "A605" },
  { name: "Samsung Galaxy A70", code: "A705" },
  { name: "Samsung Galaxy A70s", code: "A707" },
  { name: "Samsung Galaxy A71", code: "A715" },
  { name: "Samsung Galaxy A71 5G", code: "A716" },
  { name: "Samsung Galaxy A72", code: "A725" },
  { name: "Samsung Galaxy A72 5G", code: "A726" },
  { name: "Samsung Galaxy A73 5G", code: "A736" },
  { name: "Samsung Galaxy A7 2018", code: "A750" },
  { name: "Samsung Galaxy A80", code: "A805" },
  { name: "Samsung Galaxy A90 5G", code: "A908" },
  { name: "Samsung Galaxy M01 Core", code: "M013" },
  { name: "Samsung Galaxy M01", code: "M015" },
  { name: "Samsung Galaxy M02", code: "M022" },
  { name: "Samsung Galaxy M02s", code: "M025" },
  { name: "Samsung Galaxy M10", code: "M105" },
  { name: "Samsung Galaxy M10s", code: "M107" },
  { name: "Samsung Galaxy M11", code: "M115" },
  { name: "Samsung Galaxy M12", code: "M127" },
  { name: "Samsung Galaxy M13", code: "M135" },
  { name: "Samsung Galaxy M13 5G", code: "M136" },
  { name: "Samsung Galaxy M14 5G", code: "M146" },
  { name: "Samsung Galaxy M15 5G", code: "M156" },
  { name: "Samsung Galaxy M20", code: "M205" },
  { name: "Samsung Galaxy M21", code: "M215" },
  { name: "Samsung Galaxy M22", code: "M225" },
  { name: "Samsung Galaxy M23 5G", code: "M236" },
  { name: "Samsung Galaxy M30", code: "M305" },
  { name: "Samsung Galaxy M30s", code: "M307" },
  { name: "Samsung Galaxy M31", code: "M315" },
  { name: "Samsung Galaxy M31s", code: "M317" },
  { name: "Samsung Galaxy M32", code: "M325" },
  { name: "Samsung Galaxy M32 5G", code: "M326" },
  { name: "Samsung Galaxy M33 5G", code: "M336" },
  { name: "Samsung Galaxy M34 5G", code: "M346" },
  { name: "Samsung Galaxy M35 5G", code: "M356" },
  { name: "Samsung Galaxy M42 5G", code: "M426" },
  { name: "Samsung Galaxy M51", code: "M515" },
  { name: "Samsung Galaxy M52 5G", code: "M526" },
  { name: "Samsung Galaxy M53 5G", code: "M536" },
  { name: "Samsung Galaxy M54 5G", code: "M546" },
  { name: "Samsung Galaxy M62", code: "M625" },
  { name: "Samsung Galaxy F02s", code: "E025" },
  { name: "Samsung Galaxy F04", code: "E045" },
  { name: "Samsung Galaxy F13", code: "E135" },
  { name: "Samsung Galaxy F14 5G", code: "E146" },
  { name: "Samsung Galaxy F15", code: "E156" },
  { name: "Samsung Galaxy F23 5G", code: "E236" },
  { name: "Samsung Galaxy F42 5G", code: "E426" },
  { name: "Samsung Galaxy F52 5G", code: "E526" },
  { name: "Samsung Galaxy F62", code: "E625" },
  { name: "Samsung Galaxy S7", code: "G930" },
  { name: "Samsung Galaxy S7 Edge", code: "G935" },
  { name: "Samsung Galaxy S8", code: "G950" },
  { name: "Samsung Galaxy S8+", code: "G955" },
  { name: "Samsung Galaxy S9", code: "G960" },
  { name: "Samsung Galaxy S9+", code: "G965" },
  { name: "Samsung Galaxy S10e", code: "G970" },
  { name: "Samsung Galaxy S10", code: "G973" },
  { name: "Samsung Galaxy S10+", code: "G975" },
  { name: "Samsung Galaxy S10 5G", code: "G977" },
  { name: "Samsung Galaxy S10 Lite", code: "G770" },
  { name: "Samsung Galaxy S20", code: "G980" },
  { name: "Samsung Galaxy S20+", code: "G985" },
  { name: "Samsung Galaxy S20 Ultra", code: "G988" },
  { name: "Samsung Galaxy S20 FE", code: "G780" },
  { name: "Samsung Galaxy S20 FE 5G", code: "G781" },
  { name: "Samsung Galaxy S21", code: "G991" },
  { name: "Samsung Galaxy S21+", code: "G996" },
  { name: "Samsung Galaxy S21 Ultra", code: "G998" },
  { name: "Samsung Galaxy S21 FE", code: "G990" },
  { name: "Samsung Galaxy S22", code: "S901" },
  { name: "Samsung Galaxy S22+", code: "S906" },
  { name: "Samsung Galaxy S22 Ultra", code: "S908" },
  { name: "Samsung Galaxy S23", code: "S911" },
  { name: "Samsung Galaxy S23+", code: "S916" },
  { name: "Samsung Galaxy S23 Ultra", code: "S918" },
  { name: "Samsung Galaxy S23 FE", code: "S711" },
  { name: "Samsung Galaxy S24", code: "S921" },
  { name: "Samsung Galaxy S24+", code: "S926" },
  { name: "Samsung Galaxy S24 Ultra", code: "S928" },
  { name: "Samsung Galaxy S24 FE", code: "S721" },
  { name: "Samsung Galaxy S25", code: "S931" },
  { name: "Samsung Galaxy S25+", code: "S936" },
  { name: "Samsung Galaxy S25 Edge", code: "S937" },
  { name: "Samsung Galaxy S25 Ultra", code: "S938" },
  { name: "Samsung Galaxy S25 FE", code: "S731" },
  { name: "Samsung Galaxy S26", code: "S942" },
  { name: "Samsung Galaxy S26+", code: "S947" },
  { name: "Samsung Galaxy S26 Ultra", code: "S948" },
  { name: "Samsung Galaxy Note", code: "N700" },
  { name: "Samsung Galaxy Note 2", code: "N710" },
  { name: "Samsung Galaxy Note 3", code: "N900" },
  { name: "Samsung Galaxy Note 4", code: "N910" },
  { name: "Samsung Galaxy Note 5", code: "N920" },
  { name: "Samsung Galaxy Note 8", code: "N950" },
  { name: "Samsung Galaxy Note 9", code: "N960" },
  { name: "Samsung Galaxy Note 10", code: "N970" },
  { name: "Samsung Galaxy Note 10+", code: "N975" },
  { name: "Samsung Galaxy Note 10+ 5G", code: "N976" },
  { name: "Samsung Galaxy Note 10 Lite", code: "N770" },
  { name: "Samsung Galaxy Note 20", code: "N980" },
  { name: "Samsung Galaxy Note 20 Ultra", code: "N985" },
  { name: "Samsung Galaxy Note 20 Ultra 5G", code: "N986" },
  { name: "Samsung Galaxy Z Flip", code: "F700" },
  { name: "Samsung Galaxy Z Flip 5G", code: "F707" },
  { name: "Samsung Galaxy Z Flip3", code: "F711" },
  { name: "Samsung Galaxy Z Flip4", code: "F721" },
  { name: "Samsung Galaxy Z Flip5", code: "F731" },
  { name: "Samsung Galaxy Z Flip6", code: "F741" },
  { name: "Samsung Galaxy Z Flip7 FE", code: "F761" },
  { name: "Samsung Galaxy Z Flip7", code: "F766" },
  { name: "Samsung Galaxy Z Fold", code: "F900" },
  { name: "Samsung Galaxy Z Fold2", code: "F916" },
  { name: "Samsung Galaxy Z Fold3", code: "F926" },
  { name: "Samsung Galaxy Z Fold4", code: "F936" },
  { name: "Samsung Galaxy Z Fold5", code: "F946" },
  { name: "Samsung Galaxy Z Fold6", code: "F956" },
  { name: "Samsung Galaxy Z Fold Special Edition", code: "F958" },
  { name: "Samsung Galaxy Z Fold7", code: "F966" },
  { name: "Samsung Galaxy Z TriFold", code: "F968" },
  { name: "Samsung Galaxy J2", code: "J200" },
  { name: "Samsung Galaxy J2 Prime", code: "G532" },
  { name: "Samsung Galaxy J2 Core", code: "J260" },
  { name: "Samsung Galaxy J3", code: "J300" },
  { name: "Samsung Galaxy J3 2016", code: "J320" },
  { name: "Samsung Galaxy J3 2017", code: "J330" },
  { name: "Samsung Galaxy J4", code: "J400" },
  { name: "Samsung Galaxy J4+", code: "J415" },
  { name: "Samsung Galaxy J5", code: "J500" },
  { name: "Samsung Galaxy J5 2016", code: "J510" },
  { name: "Samsung Galaxy J5 Prime", code: "G570" },
  { name: "Samsung Galaxy J5 2017", code: "J530" },
  { name: "Samsung Galaxy J6", code: "J600" },
  { name: "Samsung Galaxy J6+", code: "J610" },
  { name: "Samsung Galaxy J7", code: "J700" },
  { name: "Samsung Galaxy J7 Prime", code: "G610" },
  { name: "Samsung Galaxy J7 Next", code: "J701" },
  { name: "Samsung Galaxy J7 Pro", code: "J730" },
  { name: "Samsung Galaxy J8", code: "J810" },
  { name: "Samsung Galaxy XCover5", code: "G525" },
  { name: "Samsung Galaxy XCover6 Pro", code: "G736" },
  { name: "Samsung Galaxy XCover7", code: "G556" },
  { name: "Samsung Galaxy XCover7 Pro", code: "G766" }
];
